# Generated by Django 3.0 on 2022-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220313_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
