# Generated by Django 3.0 on 2022-04-10 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicRoomChat',
            new_name='PublicChatRoom',
        ),
        migrations.RenameModel(
            old_name='PublicRoomChatMessage',
            new_name='PublicChatRoomMessage',
        ),
    ]
