# Generated by Django 3.0 on 2022-04-10 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_auto_20220410_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicChatRoomMessage',
            new_name='PublicRoomChatMessage',
        ),
        migrations.AlterField(
            model_name='publicchatroom',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to chat room.', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
